### PR TITLE
WIP: Enable CircleCI

### PR DESCRIPTION
**Pull request by Xorima**
This PR will enable Circle CI Integration testing

### CODE REVIEW

**Comment by damacus** [comment]
psst, you need a Dangerfile

**Comment by Xorima** [comment]
Can I get some advice on the failing tests due to a bundle install not being run, how is the best way to approach this issue? (I haven't used gems before)

**Comment by gdavison** [comment]
You might have some trouble with this one, it’s a Poise-based cookbook, so it probably needs lots of those gems

**Comment by Xorima** [comment]
If we had a bundle install before the `chef exec delivery` do you think this would work?

**Comment by damacus** [comment]
I think we actually just need to look at removing poise once you've finished with most to the other problems

**Comment by Xorima** [comment]
If you want to merge this @damacus feel free to, for now I will focus on the simpler circleci cookbooks and we can revisit this one at a later date

**Pull request merged**
