### PR TITLE
Add additional advertise_addr_ipv* attributes

### PR DESCRIPTION
**Pull request by edgarasg**
Signed-off-by: Edgaras Giedrė <edgaras.giedre@hostinger.com>

# Description

Adds additional attributes:
`advertise_addr_ipv4`
`advertise_addr_ipv6`

https://www.consul.io/docs/agent/options#advertise_addr_ipv4
https://www.consul.io/docs/agent/options#advertise_addr_ipv6

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
hi @edgarasg can you add a changeling here please? 

And likewise, there are probably some missing tests here.

**Comment by edgarasg** [comment]
Sure, I can add a changelog entry.

Do we need tests for these attributes explicitly?

**Comment by ramereth** [comment]
@edgarasg no I don't think so, thanks for asking though!

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edgarasg** [comment]
Changelog entry added.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [4.5.0](https://github.com/sous-chefs/consul/releases/tag/4.5.0)

**Pull request merged**
