### PR TITLE
Restore the ability to set a custom open file limit

### PR DESCRIPTION
**Pull request by RoboticCheese**
This seems to have existed, at least for Upstart, in [older versions](https://github.com/sous-chefs/consul/blob/v0.11.1/attributes/default.rb#L123) of the cookbook, but disappeared with the conversion to poise-service.

The Kitchen suites have a pretty basic default config that I was hesitant to mess with, hence the new test suite, which could also be used to validate other config overrides in the future. If the additional build time is going to be a problem, I can rip those tests back out or put them in the default suite.

Signed-off-by: Jonathan Hartman <j@hartman.io>

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
If you can get this testing I'm good to merge it. 

Eventually we need to de-poise this cookbook. So I'm a little wary of touching it until then :)

**Comment by RoboticCheese** [comment]
Working on the failing tests today. The errors seem to have been around for a while and now I'm getting different ones on my dev machine, which is always fun. Looks like a good chunk of it is conflicts between what comes with the Chef-DK and what `chef exec bundle install` is trying to pull down with poise-boiler.

Is there a preferred example of the style y'all follow for non-Poise custom resources? The extra complexity from those deps has hit us as well, enough that I might be able to justify putting some work hours into some de-Poise-ing.

**Comment by Xorima** [comment]
Hey
Thank you for the PR. We are closing due to inactivity. 
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Thanks

Sous Chefs

**Pull request closed without merging**
