### PR TITLE
Consul 1.5.x ACLs

### LINKED ISSUE #520: Support Consul 1.4.0+ ACL system
Placeholder issue, as we need Diplomat to be updated before but a simple resource matching the name of a token on the new ACL system will fail.

For example, this resource will fail on Consul 1.4.x:

```ruby
consul_acl 'anonymous' do
   xxxxx
end
```

Related to https://github.com/WeAreFarmGeek/diplomat/issues/193

### PR DESCRIPTION
**Pull request by scalp42**
# Description

Add 3 new resources:

- `consul_token`
- `consul_policy`
- `consul_role`

## Issues Resolved

#520

### CODE REVIEW

**Comment by scalp42** [comment]
It doesn't seem doable until https://github.com/hashicorp/consul/issues/4977 ships.

**Comment by scalp42** [comment]
Going to resume work once https://github.com/WeAreFarmGeek/diplomat/pull/196 is merged as Consul 1.5.0 re-allows custom `AccessorID` and `SecretID`.

**Comment by scalp42** [comment]
One of the issues when updating ACL tokens and comparing policies is that Consul endpoint returns **both** policy `ID` and `Name` and we only use the later to compare.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by freakinhippie** [comment]
Is this still a WIP or has it been completed and is waiting to be merged?

**Comment by scalp42** [comment]
Not worth much but we've been using it in production since then.

**Comment by kjbweb** [comment]
> Not worth much but we've been using it in production since then.

Are you just being held up by process here?  Is there anything I can do to help?  

Keen to see this PR get merged as we've been pushed to upgrade consul before Chef was able to manage the ACL's.

**Comment by scalp42** [comment]
I think it's linting rules blocking this PR. Changelog should be handled by the person bumping the cookbook I believe.

Regarding tests, ours is tested through InSpec and kitchen instead of unit testing which we like more.

Otherwise, running in production with seperated `consul_policy` and `consul_token`:

```ruby
 # NOTE: set the anonymous token & policy if ACLs are enabled,
  # mainly used for DNS requests as you can't pass a token
  consul_policy 'anonymous' do
    description 'Anynomous policy'
    auth_token(
      WoLibs::Aws::Kms.decrypt(node[cookbook_name]['acl']['tokens']['master'],
                               profile: node[cookbook_name]['aws']['profile'])
    )
    rules <<-HCL.gsub(/^\s{4}/, '')
      node_prefix "" {
        policy = "read"
      }
      service_prefix "" {
        policy = "read"
      }
      operator = "read"
    HCL
    action :create
    retries 5
    retry_delay 5
    only_if do
      ::HTTParty.get(
        "http://localhost:#{node[cookbook_name]['config']['ports']['http']}/v1/acl/list",
        headers: { 'X-Consul-Token' => WoLibs::Aws::Kms.decrypt(node[cookbook_name]['acl']['tokens']['master'], profile: node[cookbook_name]['aws']['profile']) }
      ).code == 200
    end
    ignore_failure false
    sensitive true
  end

  consul_token 'Anonymous Token' do
    policies ['anonymous']
    auth_token(
      WoLibs::Aws::Kms.decrypt(node[cookbook_name]['acl']['tokens']['master'],
                               profile: node[cookbook_name]['aws']['profile'])
    )
    action :create
    retries 5
    retry_delay 10
    only_if do
      ::HTTParty.get(
        "http://localhost:#{node[cookbook_name]['config']['ports']['http']}/v1/acl/list",
        headers: { 'X-Consul-Token' => WoLibs::Aws::Kms.decrypt(node[cookbook_name]['acl']['tokens']['master'], profile: node[cookbook_name]['aws']['profile']) }
      ).code == 200
    end
    ignore_failure false
    sensitive true
  end
```

**Comment by tas50** [comment]
Thanks @scalp42

**Pull request merged**
