### PR TITLE
[Major] Rewrite resources to get rid of poise

### LINKED ISSUE #551: Poise dependency is abandoned
## Brief Description

The cookbook depends on [poise](https://github.com/poise/poise), which is now archived and abandoned. This should be removed to avoid future cookbook breakage.

## Cookbook version

3.0.0

## Chef-Infra Version

Any

## Platform details

Any

### PR DESCRIPTION
**Pull request by josqu4red**
# Description

Port resources to use Chef native framework, and drop deprecated poise dependencies.
Specs are not ported since none were added for newest resources (policy/role/etc).

This is a work in progress, it has been started under criteo-forks/consul-cookbook (https://github.com/criteo-forks/consul-cookbook/pull/19), which is not up-to-date with sous-chefs.
Most rewritten resources are currently in use in our environment (not newest ones such as policy/role/token).
Some resources (git & package install) are not ported, which we chose not to keep in the fork.
Feedback and/or help is very welcomed :)

## Issues Resolved

Fixes #551 #555 #590

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by n8dagr87** [comment]
@ramereth Looks like [nssm PR #43](https://github.com/criteo-cookbooks/nssm/pull/43) was merged to drop windows dependency - is this ready to rerun checks and merge (assuming they pass)?

**Comment by ramereth** [comment]
@n8dagr87 unfortunately it looks like the `nssm_install` needs to have `unified_mode true` set for this to move forward.

**Comment by josqu4red** [comment]
Fix incoming https://github.com/criteo-cookbooks/nssm/pull/45

**Comment by josqu4red** [comment]
Compilation fails with Chef 17.1.35 upward but not with 17.0.242. Suggestions welcome :/

**Comment by ramereth** [comment]
@josqu4red You need to change the following:
```diff
diff --git a/recipes/default.rb b/recipes/default.rb
index 4116277..e58279d 100644
--- a/recipes/default.rb
+++ b/recipes/default.rb
@@ -23,13 +23,13 @@ end
 
 service_name = node['consul']['service_name']
 config = consul_config service_name do |r|
-  node['consul']['config'].each_pair { |k, v| r.send(k, v) }
+  node['consul']['config'].each_pair { |k, v| send(k.to_sym, v) }
   notifies :reload, "consul_service[#{service_name}]", :delayed
 end
 
 install = consul_installation node['consul']['version'] do |r|
   if node['consul']['installation']
-    node['consul']['installation'].each_pair { |k, v| r.send(k, v) }
+    node['consul']['installation'].each_pair { |k, v| send(k.to_sym, v) }
   end
 end
 
@@ -44,6 +44,6 @@ consul_service service_name do |r|
     group node['consul']['service_group']
   end
   if node['consul']['service']
-    node['consul']['service'].each_pair { |k, v| r.send(k, v) }
+    node['consul']['service'].each_pair { |k, v| send(k.to_sym, v) }
   end
 end
```

**Comment by josqu4red** [comment]
@ramereth nice, thanks. Any hint on what changed ? I don't see this mentionned in Chef changelog.

**Comment by ramereth** [comment]
@josqu4red we're in the process of removing circleci/danger from repos. Can you please go ahead and remove `Dangerfile` and `.circleci/config.yml` in this PR? That should remove the remaining CI errors.

I'm not sure why that changed but I noticed the `r` variable was empty when I was debugging. So maybe something changed internally that wasn't meant to be a public API.

**Review by ramereth — APPROVED** [review]

**Review by detjensrobert — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [5.0.0](https://github.com/sous-chefs/consul/releases/tag/5.0.0)

**Pull request merged**
