### PR TITLE
Clarify README re: restarts of the Consul service when it gets installed/updated

### PR DESCRIPTION
**Pull request by gdavison**
Triggers a restart of the Consul service when it gets installed/updated

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jeffbyrnes** [comment]
@gdavison I feel as though there are Reasons™ why this cookbook doesn’t auto-restart Consul, but perhaps Consul has gained abilities where auto-restarting is less or not problematic.

**Comment by gdavison** [comment]
@jeffbyrnes Yes, I was doing some digging around and came across that. I'm going to update the PR to make it a documentation change :)

**Comment by gdavison** [comment]
This is now a documentation-only update

**Comment by Xorima** [comment]
Hey, 

Thank you for the PR. We are closing due to inactivity. 
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Sous Chefs

**Pull request closed without merging**
